change to postgredb base
hisaotoriyama/fjord_memo pull request #1
Opened 2020-09-05 11:36 UTC by hisaotoriyama

PostgresDB化にしましたのでご確認お願いいたします。

2020-09-09 04:11 UTC, komagata requested changes

2020-09-09 04:11 UTC, komagata commented on memo.rb
> +  connection = PG.connect(dbname: 'memodb', port: '5432')
この箇所が何度も出てきていて、dbnameやportが変わった時に全部の場所を修正するのが大変なので共通化できるといいかもです。

2020-09-09 04:11 UTC, komagata commented on memo.rb
> +  id_num = params['id'].to_i
この関数（メソッド）は`id_num`を引数としてとるようにすれば汎用性が大きく上がりそうです。

現状ですとparams['id']のみを想定して作られていますが、例えばこのアプリがWebアプリではなくTerminalのCLIのメモアプリになったとしても上記のようにしてあれば関数の中身は変更せずに対応できるようになります。

2020-09-09 13:35 UTC, hisaotoriyama commented on memo.rb
> +  connection = PG.connect(dbname: 'memodb', port: '5432')
PG.connectをメソッド化しました（一番下に加えました）。

2020-09-09 13:36 UTC, hisaotoriyama commented on memo.rb
> +  id_num = params['id'].to_i
id_num, todo, detailいずれも、どのメソッドについてもメソッドから外しました。

2020-09-09 13:36 UTC, hisaotoriyama commented
いただいたコメントに基づき修正しました。非常に学習になります。ありがとうございます。

2020-09-10 02:53 UTC, komagata commented
> change to postgredb base

postgresもしくはpostgresqlが正しい名前になります〜

2020-09-10 02:57 UTC, komagata requested changes

2020-09-10 02:57 UTC, komagata commented on memo.rb
> +  id_num = params['id'].to_i
`id`だけの方が簡潔でいいと思います〜

2020-09-10 02:57 UTC, komagata commented on memo.rb
> +  db_connect.exec("DELETE FROM memo_table WHERE id ='#{id_num}';")
SQLに文字列を入れるとSQL Injectionの原因となるため、プリペアードステートメントに類する機能を使ってください〜

[PostgreSQLのバルクインサートをRubyからPrepared Statementで実行 \- Qiita](https://qiita.com/suzuki-navi/items/7879b708b4f38b003444)

2020-09-10 14:08 UTC, hisaotoriyama commented on memo.rb
> +  db_connect.exec("DELETE FROM memo_table WHERE id ='#{id_num}';")
なるほど。了解しました。早速、

  db_connect.prepare("insert", prepared_stmt)
  db_connect.exec_prepared("insert", prepared_stmt_data)

とやって走らせているのですが、
2020-09-10 22:55:16 - PG::InvalidSqlStatementName - ERROR:  prepared statement "insert" does not exist:
        memo.rb:99:in `exec_prepared'
のエラ〜メッセージが出ています。exec_preparedについて調査しておりますがまだ回答見つかっておりません。明日も引き続き対応します。

2020-09-10 22:39 UTC, hisaotoriyama commented on memo.rb
> +  id_num = params['id'].to_i
了解しました。おっしゃる通りです。

2020-09-10 23:15 UTC, hisaotoriyama commented on memo.rb
> +  db_connect.exec("DELETE FROM memo_table WHERE id ='#{id_num}';")
いろいろ検索しまくっていましたが、日報でみなさん導入されていることわかりました。今頃気がつきました。日報を参考にします。

2020-09-12 04:08 UTC, hisaotoriyama commented on memo.rb
> +  db_connect.exec("DELETE FROM memo_table WHERE id ='#{id_num}';")
修正しました。ただprepare→exec_preparedで最初やっていたのですが「"insert"が認識されない」というエラーが出てしまい稼働しませんでした。よくみても間違っているとは思えず時間を費やしてしまい、なかなか終わらなかったので他の方の日報とかを参考にし、execの1行で全て修正しました。

【稼働しなかったプログラミング】
  # Prepared Statementの準備。insert_funcを定義。
   db_connect.prepare("insert", "INSERT INTO memo_table (todo, detail) VALUES ($1, $2)")
  # SQL実行
   db_connect.exec_prepared("insert", [todo,detail])

2020-09-12 09:49 UTC, komagata commented
こちら、本来一つ前のDBを使わないアプリの時点で指摘すべきことをこの段階になって申し訳ないのですが、リソース設計に置いてはHTTP Verb（動詞）+ URL（名詞）の組み合わせが原則となります。

このリソース設計・RESTの考え方については下記のプラクティスでやっている内容ですので書籍の「Webを支える技術」などを復習いただければわかりやすいかと思います。

[REST の考え方を理解する](https://bootcamp.fjord.jp/practices/154)

それを踏まえて下記ですとURLが動詞になっているので修正お願い致します。

`POST /create`
`DELETE /delete/1234`

2020-09-12 12:13 UTC, hisaotoriyama commented
ご指摘の点修正しました。ありがとうございます。

2020-09-13 01:43 UTC, komagata requested changes

2020-09-13 01:43 UTC, komagata commented on memo.rb
>  get '/show/:id' do
showも名詞なので他の表現が良いと思います。

アプリ全体がmemoを表しているとして、そのIDを絞り込む意味で、`/1234`

または`/memos/1234`などはいかがでしょうか。

2020-09-13 13:11 UTC, hisaotoriyama commented on memo.rb
>  get '/show/:id' do
了解しました。showについては、/memos/:idとし、また一方、editについては同じ考えを入れつつ、でもshowとの違いを出す必要があること、からeditを名詞として/memos/:id/editに修正しました。

2020-09-14 02:59 UTC, komagata requested changes

2020-09-14 02:59 UTC, komagata commented on memo.rb
> +  results = db_connect.exec('SELECT * FROM memo_table;')
```suggestion
  results = db_connect.exec('SELECT * FROM memo_table')
```

セミコロン不要です〜

2020-09-14 02:59 UTC, komagata commented on memo.rb
> +  db_connect.exec('UPDATE memo_table SET todo =$2, detail = $3 WHERE id = $1', [id, todo, detail])
```suggestion
  db_connect.exec('UPDATE memo_table SET todo = $2, detail = $3 WHERE id = $1', [id, todo, detail])
```

2020-09-14 10:05 UTC, hisaotoriyama commented on memo.rb
> +  db_connect.exec('UPDATE memo_table SET todo =$2, detail = $3 WHERE id = $1', [id, todo, detail])
修正しました。全体を見直し修正もう一箇所修正しました。

2020-09-14 10:05 UTC, hisaotoriyama commented on memo.rb
> +  results = db_connect.exec('SELECT * FROM memo_table;')
セミコロン削除いたしました。

2020-09-15 05:34 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-17 10:46 UTC, merged